apiVersion: 1.0.0
kind: Plugin
metadata:
  name: MongoDB Storage
  description: MongoDB Storage Plugin for Reekoh IoT Platform.
  icon: asset/icon/reekoh200x200.png
  signupLink: https://myservice.com/signup # ??
  type: Storage
  price: 0
  tags:
    - storage
    - mongo
    - mongodb
    
  release:
    version: 1.0.0
    notes: path/to/RELEASENOTESv1.0.0.md # ??
    documentation: README.md
    config:
      connString:
        label: Connection String
        type: String
        maxLength: 1000
        required: true
        help: "Specify the full MongoDB Connection String."
      collection:
        label: Collection
        type: String
        maxLength: 1000
        required: true
        help: "Specify the database collection to insert the data to."
